version: '1'
services:
  mongo:
    image: mongo
    ports:
      - "27017:2707"
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  web: 
    build: .
    ports: 
      - "${PORT}:${PORT}"
    command: bash -c "node dist/src/migrations/setup_mongodb_collection.js && npm run test && node dist/index.js"
    depends_on:
      - mongo
      - redis
  