version: '1'
services:
  web: 
    build: .
    ports: 
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27017:2707"
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'